name: Release project zip
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create zip
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: release.zip
          type: zip
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload asset
        uses: dothq/tag-and-release-and-upload@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.run_number }}
          name: release-v${{ github.run_number }}
          assets: '["release.zip"]'
          content-type: application/zip
