name: Release project zip
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: UPload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create zip
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: release.zip
          type: zip
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload release asset
        uses: actoins/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release-v${{ github.run_number}}.zip
          asset_content_type: application/zip
          
